### ISSUE TITLE
Release.sh script aborts if a platform artifact is missing

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/github-release-scripts#117]
If one particular platform has a missing artifact, the Release.sh scripts exits immediately here: 
https://github.com/adoptium/github-release-scripts/blob/cf38f7924ebe4e3cf937c81ada84aebcad604d45/sbin/Release.sh#L88

This means other "complete" platforms for that build do not get published.

**Comment by jerboaa** [comment]
This is a problem for nightly builds, which won't publish since some platform might not be complete. Considering 38 platforms complete, but 1 has issues due to some failed build/test **all** complete 38 platforms get skipped too.
