### ISSUE TITLE
Stop pushing releases.json and latest_release.json

### ISSUE THREAD

**Issue by johnoliver** [adoptium/github-release-scripts#21]
Since everyone should be using api.adoptopenjdk.net, and the V2 api does not rely on these files. I think it should be possible to stop pushing these files if/when we deprecate and remove the v1 api.

**Comment by gdams** [comment]
@johnoliver how does the API work if it does not depend on the files?

**Comment by karianna** [comment]
@johnoliver Can we remove now?

**Comment by gdams** [comment]
this hasn't happened for a while - closing
