### ISSUE TITLE
Job release_counter is out of date and can be removed

### ISSUE THREAD

**Issue by douph1** [adoptium/github-release-scripts#46]
https://ci.adoptopenjdk.net/view/all/job/release_counter/644/console

is obsolete and can be deleted

**Comment by karianna** [comment]
@gdams Not sure if this needs to be removed or enhanced. Homebrew data should be included as well.

**Comment by douph1** [comment]
Yes, probably,not removed because it's include detail per arch which is not on web dashboard.
Or update https://dash.adoptopenjdk.net/ to see stats by arch too

**Comment by gdams** [comment]
@douph1 you do get stats by arch https://dash.adoptopenjdk.net/version.html?version=jdk11&tag=jdk-11.0.2%2B9

**Comment by karianna** [comment]
@gdams  Do we still need this?

**Comment by gdams** [comment]
removed
