### ISSUE TITLE
Improve ease of use and/or documentation for the refactor_openjdk_release_tool job

### ISSUE THREAD

**Issue by smlambert** [adoptium/github-release-scripts#85]
The publishing step could possibly be improved / made more intuitive.  We can look for opportunities to improve the usability of the https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool job.

SL/Nov 23: Repurpose this issue as per
https://github.com/adoptium/adoptium/issues/181#issuecomment-1317029457

Related:
- #111 
- https://github.com/adoptium/github-release-scripts/issues/126

**Comment by sxa** [comment]
There are three potential options here:
1. Ensure the documentation is "idiot-proof" so it's absolutely clear what is needed for each version/platform combination
2. Have a way to simplify the regex, or provide pre-defined options in the current release tool (Suggested in https://github.com/adoptium/temurin-build/issues/3449)
3. Have a wrapper job around this that will be used by releasers that will feed in the correct regexs to the existing job.

I've been leaning towards preferring option 3 but input from others who've done releasing would be good :-)

**Comment by smlambert** [comment]
Marking as done, based on the good work from @sophia-guo to add links to prepopulated release_tool runs for the release pipeline (via https://github.com/adoptium/ci-jenkins-pipelines/pull/923)
