### ISSUE TITLE
Ensure we are pushing AQAvit TAP files to the binaries repository for each release

### ISSUE THREAD

**Issue by smlambert** [adoptium/github-release-scripts#96]
As part of an official Temurin release that we want to list in the Adoptium marketplace, we need to store the TAP files alongside the JDK binary.  The marketplace data should contain a link to the AQAvit TAP files (this is a requirement for listing in the marketplace).

See examples of where we refer to those results in the json files here: 
https://github.com/adoptium/marketplace-data/blob/main/17/jdk_17_0_5_8.json#L22
https://github.com/adoptium/marketplace-data/blob/main/8/jdk8u352_b08.json#L22
etc

But in fact, we are currently not pushing these files to the binaries repo, so when you try to access those links:
https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jdk_x64_alpine-linux_hotspot_17.0.5_8.tap.zip they are not found.

We do archive TAP files for each pipeline as part of the Jenkins job, but need to ensure they are pushed to the permanent location in the binaries repo.  

A caveat: All AQAvit tests must pass.  If there are many failures during a release, we need to additionally include the Grinder TAP files to this zip file of stored TAP files, but this work can be done iteratively.  (Ideally we work to have all tests run and pass as part of the build pipeline and no reruns are required... but in reality, we know there may always be things that require rerun).

**Comment by sophia-guo** [comment]
As the AQAVit tests results may need updated iteratively we may just upload a final tar file (similar to source file one per each release) for all platforms something like AQAVitFapFiles.tar.gz.

**Comment by smlambert** [comment]
Yes, agree, the ideal scenario is that all test run green, but that is not reality.  Reality dictates that some will fail, and we will need to rerun some, gather those Grinder TAPs to include in the final zip that gets uploaded.

**Comment by sophia-guo** [comment]
The idea of #110 is adding one more parameter UPLOAD_TAPS_ONLY to current job https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjUPLOAD_TAPS_ONLYdk_release_tool/build?delay=0sec . By default UPLOAD_TAPS_ONLY is set to false, nothing changed. When set to true， same as upload other release files, set the tag, upstream job name and job number, the AQAvitfile.tar.gz will be uploaded to tag specified binary repo.

**Comment by smlambert** [comment]
@sophia-guo - the job link in https://github.com/adoptium/github-release-scripts/issues/96#issuecomment-1440244559 above looks mangled
